# Generated by Django 5.2.5 on 2025-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
                ('produits', models.ManyToManyField(blank=True, related_name='rayons', to='monApp.produit')),
            ],
        ),
    ]
