# Generated by Django 5.2.5 on 2025-09-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rayon',
            name='produits',
            field=models.ManyToManyField(related_name='rayons', to='monApp.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='monApp.statut'),
        ),
    ]
