# Generated by Django 5.2.5 on 2025-09-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_statut_produit_datefabrication_alter_rayon_produits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='idStatut',
            new_name='idStatus',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='libelle',
            new_name='libelleStatus',
        ),
    ]
