# Generated by Django 5.2.5 on 2025-09-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_rename_idstatut_statut_idstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('produits', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monApp.produit')),
                ('rayons', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon')),
            ],
        ),
    ]
